### ISSUE TITLE
Smaller, More Frequent Releases

### ISSUE THREAD

**Issue by svozza** [sanctuary-js/sanctuary#297] opened 2016-12-01 15:06 UTC
I'm very excited about v0.12 of Sanctuary but also a bit scared. We have changed a huge amount of things so the surface area for bugs in this release is quite large. In future, I would like to see us do more frequent but smaller releases to derisk things. For example, I don't see why PRs similar to `S.prop` and `S.path` couldn't be released together as soon as they're done as part of a minor version update. What are people's thoughts?

**Comment by davidchambers** [comment] 2016-12-02 02:28
I'm in favour of this too. I do consider the current situation exceptional, though. Breaking changes to the Fantasy Land spec, the creation of sanctuary-type-classes, and major changes to sanctuary-def have come together to create two very large pull requests (#232 and #216). After we do eventually release v0.12.0 I hope we can switch to making smaller releases every month or two.

**Comment by EvanBurchard** [comment] 2016-12-02 06:09
If this isn't the place to discuss this, let me know, but I'm curious what 1.0.0 is being saved for. To me, dropping functions out of the API signal a major change. Just wondering what the thoughts are there. 

I'm considering adopting semantic versioning alternatives ([comver](https://github.com/staltz/comver) and [monotonic](http://blog.appliedcompscilab.com/monotonic_versioning_manifesto/)) for some projects, but they don't seem to address the significance of a 1.0.0 version. Maybe they don't need it. Is it possible that sanctuary is doing comver now (with the minor signifying major, and the patch signifying minor and patch)? And if that is the case, would one of these schemes (probably comver) be appropriate starting at 1.0.0?

**Comment by svozza** [comment] 2016-12-02 10:42
Interesting, I was going to create a separate issue for our `1.0.0` strategy, I would like to see us move quickly on this. I would hate for us to end up like Ramda and be perpetually in beta (over 3 years and counting!).

**Comment by davidchambers** [comment] 2016-12-12 20:36
I'll close this issue as we all agree that we should never again go six months between releases. :)

As for v1.0.0, I agree that we should release it sooner rather than later. The next release should not be v1.0.0, though, as so much has changed since v0.11.1 and there are likely to be some regressions. I do think the following (non-patch) release should be v1.0.0, though!

**Closed by davidchambers** 2016-12-12 20:36 UTC
