### ISSUE TITLE
toMaybe crashes on cyclic (circular) objects

### ISSUE THREAD

**Issue by mnn** [sanctuary-js/sanctuary#306] opened 2016-12-12 13:22 UTC
```js
$ node
> const S = require('sanctuary')
undefined
> S.toMaybe('')
Just("")
> const a = {};
undefined
> a.a=a;
{ a: [Circular] }
> S.toMaybe(a)
RangeError: Maximum call stack size exceeded
    at validate (xxx/node_modules/sanctuary-def/index.js:332:18)
    at Object._test (xxx/node_modules/sanctuary-def/index.js:276:14)
    at xxx/node_modules/sanctuary-def/index.js:856:53
    at chain (xxx/node_modules/sanctuary-def/index.js:82:26)
    at xxx/node_modules/sanctuary-def/index.js:854:14
    at map (xxx/node_modules/sanctuary-def/index.js:120:62)
    at recur (xxx/node_modules/sanctuary-def/index.js:843:19)
    at determineActualTypesStrict (xxx/node_modules/sanctuary-def/index.js:892:31)
    at recur (xxx/node_modules/sanctuary-def/index.js:1044:32)
    at $.test (xxx/node_modules/sanctuary-def/index.js:1079:12)
```

Version: 0.11.1

**Comment by mnn** [comment] 2016-12-12 13:35
Possible workaround is to construct a wrapping function, but it adds complexity and in case of TypeScript makes types really verbose.

```js
> S.maybeToNullable(S.toMaybe(() => a))()
{ a: [Circular] }
```

**Comment by safareli** [comment] 2016-12-12 14:30
the issue is not in actual `toMaybe` as it's just
```js
function toMaybe(x) {
  return x == null ? Nothing : Just(x);
}
S.toMaybe = def('toMaybe', {}, [a, $Maybe(a)], toMaybe);
```

so issue should be in sanctuary-def, i think it's failing because it checks if type of value passed to `toMaybe`  is same as value in  it's return which is not counting for recursive structures.

I think even this will fail:
```js
const a = {}
a.a = a
def('test', {}, [a, $Maybe(a)],  (x) => Just(x))(a)
```

**Comment by davidchambers** [comment] 2016-12-12 20:32
> so issue should be in sanctuary-def

That's right. I was able to reproduce the issue with the old version of sanctuary-def that Sanctuary currently uses:

```console
$ cd ~/github.com/sanctuary-js/sanctuary-def
$ git checkout v0.6.0
$ node --print 'const $ = require("."), a = $.TypeVariable("a"), def = $.create({checkTypes: true, env: $.env}), id = def("id", {}, [a, a], x => x), o = {}; o.o = o; id(o) === o'
/Users/dc/github.com/sanctuary-js/sanctuary-def/index.js:332
          return Left({value: x, typePath: [t], propPath: []});
                 ^

RangeError: Maximum call stack size exceeded
```

The same code works correctly with the most recent sanctuary-def release:

```console
$ git checkout v0.8.0
$ node --print 'const $ = require("."), a = $.TypeVariable("a"), def = $.create({checkTypes: true, env: $.env}), id = def("id", {}, [a, a], x => x), o = {}; o.o = o; id(o) === o'
true
```

I ran `git bisect` and determined that the problem was fixed in sanctuary-js/sanctuary-def#77. I should finish work on #232 pronto so we can merge it and release v0.12.0. If you'd like to provide encouragement you may do so [here][1].

Let's keep this issue open until v0.12.0 is released.


[1]: https://github.com/sanctuary-js/sanctuary/issues/255#issuecomment-266537281

**Comment by Avaq** [comment] 2017-02-15 13:57
I believe this issue can be closed. With the latest version of Sanctuary:

```js
> const a = {};
undefined
> a.a=a;
{ a: [Circular] }
> S.toMaybe(a)
Just({"a": <Circular>})
```

**Closed by Avaq** 2017-02-15 13:57 UTC

**Comment by davidchambers** [comment] 2017-02-15 14:50
Thanks for closing this issue, Aldwin. :)
